sonar.projectKey=bookkeeping
sonar.projectName=Bookkeeping
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=src/**/*.unit.test.ts,src/**/*.integration.test.ts,tests/**
sonar.exclusions=src/**/*.unit.test.ts,src/**/*.integration.test.ts
sonar.typescript.tsconfigPaths=tsconfig.json
