sonar.projectKey=bookkeeping
sonar.projectName=Bookkeeping
sonar.sourceEncoding=UTF-8

sonar.sources=apps/web/src
sonar.tests=apps/web/src,apps/web/tests
sonar.test.inclusions=apps/web/src/**/*.unit.test.ts,apps/web/src/**/*.integration.test.ts,apps/web/tests/**
sonar.exclusions=apps/web/src/**/*.unit.test.ts,apps/web/src/**/*.integration.test.ts
sonar.typescript.tsconfigPaths=apps/web/tsconfig.json
