// Generated by `pnpm --filter @bookkeeping/web generate:api` from the
// server's OpenAPI document. Do not edit; regenerate.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check server health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Returns the signed-in owner's income and expense category trees in picker order. Parents precede their children, protected Uncategorized entries are included, and reads never initialize or modify a missing tree. The collection is unpaginated; `nextCursor` is always null.
         */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a category
         * @description Creates a parent or a child in the signed-in owner's income or expense tree. Names are trimmed and unique within their parent scope. The request must carry a client-generated Idempotency-Key: repeating it with the same normalized payload replays the original creation, while a different payload is a conflict. A rejected request never consumes its key.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a category
         * @description One category the signed-in owner holds, as listed in its tree. A category that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Delete a category
         * @description Removes a child or a childless parent category. The child's transactions move to its parent, and a childless parent's move to that tree's Uncategorized, so no entry loses its categorization. A parent with children must be emptied first, and Uncategorized itself cannot be removed. A category that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Renames the category and/or changes its icon in one save. The tree position and kind never change, and names stay unique within their scope, case-insensitively. Uncategorized keeps its name; its icon can still change, so repeating its exact current name and icon succeeds without effect. A category that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/v1/categories/{categoryId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a category's usage
         * @description The current income and expense transactions filed under the category and the child categories it holds: the information needed before removing it. Refunds follow their expense's category and are not counted. A category that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        get: operations["getCategoryUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialize default categories
         * @description Creates any default category tree the signed-in owner is missing. Sign-up provisions the set automatically; call this after sign-up or sign-in to complete an interrupted provisioning. Idempotent: existing trees, including customized ones, are left untouched.
         */
        post: operations["initializeDefaultCategories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List category usage
         * @description How many current transactions each of the signed-in owner's categories holds, for deciding what can be removed without reading every category in turn. Only categories with at least one transaction appear; a category that is absent holds none. Refunds follow their expense's category and are never counted, and deleted transactions stop counting. The collection is unpaginated; `nextCursor` is always null.
         */
        get: operations["listCategoryUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a monthly report
         * @description The signed-in owner's server-calculated totals for one month in YYYY-MM form: income, gross expenses, refunds, net expenses, and net as exact Money objects beside the number of counted transactions. Totals follow Bangkok calendar dates, so a refund counts in the month of its own transaction date, while transfers and opening balances never count. A month with no counted transactions reports every amount as zero with a transaction count of zero; aggregates stay exact beyond JavaScript's safe integers. A malformed or impossible month is a bad request.
         */
        get: operations["getMonthlyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions
         * @description Returns the signed-in owner's current financial history, newest transaction date first, then newest recording time and identifier. Date, wallet, category, and type filters preserve transfer, parent category, refund, and ownership semantics. Pages use an opaque cursor bound to this ordering and the active filters; the server caps the requested limit.
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Create an income, expense, transfer, or refund
         * @description Records income, expense, a wallet transfer, or a refund for the signed-in owner using an exact THB amount and a real calendar date. Income and expense requests name a matching category and active owned wallet; transfers name distinct active owned source and destination wallets; refunds name an active owned receiving wallet and one of the owner's own expenses, follow the expense's category, and cannot exceed what remains of it. The request must carry a client-generated Idempotency-Key: repeating it with the same normalized payload replays the original detail, while a different payload is a conflict. A rejected request never consumes its key.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a transaction
         * @description One current transaction of the signed-in owner with its wallet, destination wallet, category, and expense link mapped exactly: money as an exact decimal string beside its currency, the transaction date as a calendar date, and the recording time as a UTC instant. A transaction that does not exist, has been deleted, belongs to another owner, or has a malformed identifier is not found alike.
         */
        get: operations["getTransaction"];
        /**
         * Update a transaction
         * @description Corrects one of the signed-in owner's transactions with an exact THB amount and a real calendar date. The transaction's type and its expense link are fixed; the wallet, category, amount, date, and note are re-validated against the owner's records, and the transaction may keep the archived wallets it already has. An expense still covers every linked refund, and a refund stays within what remains of its expense. An update that changes nothing succeeds without effect, so a client may safely retry. A transaction that does not exist, has been deleted, belongs to another owner, or has a malformed identifier is not found alike.
         */
        put: operations["updateTransaction"];
        post?: never;
        /**
         * Delete a transaction
         * @description Removes one of the signed-in owner's transactions from current history while retaining the internal record, writing its change history atomically with the deletion. An expense that still has linked refunds stays and lists them in its conflict problem; delete each refund first. Repeating a deletion succeeds without effect, so a client may safely retry. A transaction that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transactionId}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an expense's refunds
         * @description The current refunds linked to one of the owner's expenses, oldest transaction date first, with what they add up to and what is left to refund. Only a current expense has a refund allowance: a missing, deleted, foreign, malformed, or non-expense identifier is not found alike.
         */
        get: operations["getTransactionRefunds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/entry-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction entry defaults
         * @description The server-calculated starting point for the entry form: the wallet of the signed-in owner's most recently recorded transaction, or null before the first one. Deleted transactions never count.
         */
        get: operations["getTransactionEntryDefaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List wallets
         * @description Every wallet the signed-in owner holds, archived ones included, in creation order with an end-of-day balance in Bangkok. The optional `asOf` calendar date reports balances as they stood at the end of that day, counting the opening amount and every transaction dated on or before it; omitting it reports today's. A date before a wallet opened reports zero, and a malformed date or an unknown parameter is a bad request. The collection is small and unpaginated; `nextCursor` is always null.
         */
        get: operations["listWallets"];
        put?: never;
        /**
         * Create a wallet
         * @description Opens a wallet for the signed-in owner with an exact opening balance on a calendar date no later than today in Bangkok. The request must carry a client-generated Idempotency-Key: repeating it with the same payload replays the original creation, while a different payload under the same key is a conflict. A rejected request never consumes its key.
         */
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a wallet
         * @description One wallet the signed-in owner holds, with today's end-of-day balance in Bangkok. A wallet that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        /**
         * Delete a wallet
         * @description Permanently removes a wallet only when it has no current transactions, wallet changes, or retained transaction snapshots. A wallet that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        delete: operations["deleteWallet"];
        options?: never;
        head?: never;
        /**
         * Change a wallet's archived state
         * @description Archives the wallet by stamping the archived instant, or restores it by clearing it. Repeating the current state succeeds without effect, so a client may safely retry. A wallet that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        patch: operations["changeWalletArchiveState"];
        trace?: never;
    };
    "/v1/wallets/{walletId}/opening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a wallet's opening balance
         * @description Replaces the opening amount and opening date together as one resource. The date must be a calendar date no later than today in Bangkok and no later than any movement the wallet has ever carried, deleted ones included. Replacing an opening with itself succeeds without effect, so a client may safely retry. A wallet that does not exist, belongs to another owner, or has a malformed identifier is not found alike.
         */
        put: operations["replaceWalletOpening"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Category: {
            iconId: string;
            /** Format: uuid */
            id: string;
            isProtected: boolean;
            /** @enum {string} */
            kind: "income" | "expense";
            name: string;
            parentId: string | null;
        };
        CategoryCollection: {
            items: components["schemas"]["Category"][];
            page: components["schemas"]["Page"];
        };
        CategoryRemovalProblem: {
            /** @enum {string} */
            code: "protected" | "has-children" | "in-use";
            detail?: string;
            errors?: components["schemas"]["ProblemFieldError"][];
            instance?: string;
            status: number;
            title: string;
            type: string;
        } & {
            [key: string]: unknown;
        };
        CategoryUsage: {
            children: number;
            transactions: number;
        };
        CategoryUsageCollection: {
            items: components["schemas"]["CategoryUsageEntry"][];
            page: components["schemas"]["Page"];
        };
        CategoryUsageEntry: {
            /** Format: uuid */
            categoryId: string;
            transactions: number;
        };
        CreateCategoryRequest: {
            iconId: string;
            /** @enum {string} */
            kind: "income" | "expense";
            name: string;
            parent: null | {
                /** Format: uuid */
                existingId: string;
            } | {
                create: {
                    iconId: string;
                    name: string;
                };
            };
        };
        CreateTransactionRequest: {
            amount: components["schemas"]["MoneyInput"];
            /** Format: uuid */
            categoryId: string;
            note: string;
            transactionDate: string;
            /** @enum {string} */
            type: "income" | "expense";
            /** Format: uuid */
            walletId: string;
        } | {
            amount: components["schemas"]["MoneyInput"];
            /** Format: uuid */
            destinationWalletId: string;
            note: string;
            transactionDate: string;
            /** @constant */
            type: "transfer";
            /** Format: uuid */
            walletId: string;
        } | {
            amount: components["schemas"]["MoneyInput"];
            note: string;
            /** Format: uuid */
            refundOfTransactionId: string;
            transactionDate: string;
            /** @constant */
            type: "refund";
            /** Format: uuid */
            walletId: string;
        };
        CreateWalletRequest: {
            name: string;
            openingAmount: components["schemas"]["MoneyInput"];
            /** Format: date */
            openingDate: string;
            /** @enum {string} */
            type: "cash" | "bank_account" | "e_wallet";
        };
        /** @enum {string} */
        Currency: "THB";
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        HistoryRemainsProblem: {
            /** @constant */
            code: "history-remains";
            detail?: string;
            errors?: components["schemas"]["ProblemFieldError"][];
            instance?: string;
            status: number;
            title: string;
            type: string;
        } & {
            [key: string]: unknown;
        };
        Money: {
            currency: components["schemas"]["Currency"];
            value: string;
        };
        MoneyInput: {
            currency: components["schemas"]["Currency"];
            value: string;
        };
        MonthlyReport: {
            grossExpenses: components["schemas"]["Money"];
            income: components["schemas"]["Money"];
            month: string;
            net: components["schemas"]["Money"];
            netExpenses: components["schemas"]["Money"];
            refunds: components["schemas"]["Money"];
            transactionCount: number;
        };
        Page: {
            nextCursor: string | null;
        };
        ProblemDetails: {
            /** @enum {string} */
            code: "bad-request" | "conflict" | "forbidden" | "has-children" | "history-remains" | "idempotency-conflict" | "idempotency-key-required" | "in-use" | "internal-error" | "invalid-command" | "method-not-allowed" | "not-found" | "protected" | "rate-limited" | "refunds-exist" | "service-unavailable" | "unauthenticated";
            detail?: string;
            errors?: components["schemas"]["ProblemFieldError"][];
            instance?: string;
            status: number;
            title: string;
            type: string;
        } & {
            [key: string]: unknown;
        };
        ProblemFieldError: {
            code: string;
            detail?: string;
            pointer: string;
        };
        ProvisioningOutcome: {
            seededKinds: ("income" | "expense")[];
        };
        RefundsExistProblem: {
            /** @constant */
            code: "refunds-exist";
            detail?: string;
            errors?: components["schemas"]["ProblemFieldError"][];
            instance?: string;
            refunds: components["schemas"]["TransactionRefund"][];
            status: number;
            title: string;
            type: string;
        } & {
            [key: string]: unknown;
        };
        Transaction: {
            amount: components["schemas"]["Money"];
            category: {
                iconId: string;
                /** Format: uuid */
                id: string;
                name: string;
                parentName: string | null;
            } | null;
            destinationWallet: components["schemas"]["TransactionWallet"] | null;
            /** Format: uuid */
            id: string;
            note: string;
            /** Format: date-time */
            recordedAt: string;
            refundOf: {
                amount: components["schemas"]["Money"];
                /** Format: uuid */
                id: string;
                /** Format: date */
                transactionDate: string;
            } | null;
            /** Format: date */
            transactionDate: string;
            /** @enum {string} */
            type: "income" | "expense" | "transfer" | "refund";
            wallet: components["schemas"]["TransactionWallet"];
        };
        TransactionCollection: {
            items: components["schemas"]["Transaction"][];
            page: components["schemas"]["Page"];
        };
        TransactionEntryDefaults: {
            lastUsedWalletId: string | null;
        };
        TransactionRefund: {
            amount: components["schemas"]["Money"];
            /** Format: uuid */
            id: string;
            /** Format: date */
            transactionDate: string;
            wallet: components["schemas"]["TransactionWallet"];
        };
        TransactionRefunds: {
            refundedTotal: components["schemas"]["Money"];
            refunds: components["schemas"]["TransactionRefund"][];
            remaining: components["schemas"]["Money"];
        };
        TransactionWallet: {
            archived: boolean;
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "cash" | "bank_account" | "e_wallet";
        };
        UpdateCategoryRequest: {
            iconId: string;
            name: string;
        };
        UpdateTransactionRequest: {
            amount: components["schemas"]["MoneyInput"];
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            destinationWalletId?: string;
            note: string;
            transactionDate: string;
            /** Format: uuid */
            walletId: string;
        };
        Wallet: {
            archivedAt: string | null;
            balance: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            /** Format: uuid */
            id: string;
            name: string;
            openingAmount: components["schemas"]["Money"];
            /** Format: date */
            openingDate: string;
            /** @enum {string} */
            type: "cash" | "bank_account" | "e_wallet";
        };
        WalletArchiveStateRequest: {
            archived: boolean;
        };
        WalletCollection: {
            items: components["schemas"]["Wallet"][];
            page: components["schemas"]["Page"];
        };
        WalletOpeningRequest: {
            amount: components["schemas"]["MoneyInput"];
            /** Format: date */
            date: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The owner's income and expense category trees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCollection"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description A client-generated key naming this one creation */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description The created category, or the original on a replay */
            201: {
                headers: {
                    /** @description Where the created category can be retrieved */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different payload */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Uncategorized cannot be removed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryRemovalProblem"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description The category with its updated presentation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCategoryUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category's transactions and children */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryUsage"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    initializeDefaultCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trees this call seeded; empty when already complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisioningOutcome"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listCategoryUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction counts by category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryUsageCollection"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMonthlyReport: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The owner's monthly report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReport"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                categoryId?: string;
                cursor?: string;
                from?: string;
                limit?: string;
                to?: string;
                type?: "income" | "expense" | "transfer" | "refund";
                walletId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the owner's current transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionCollection"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header: {
                /** @description A client-generated key naming this one creation */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description The created transaction, or the original on a replay */
            201: {
                headers: {
                    /** @description Where the created transaction can be retrieved */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different payload */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description The updated transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Expense still has linked refunds */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RefundsExistProblem"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    getTransactionRefunds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The expense's refunds and refundable remainder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRefunds"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTransactionEntryDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry defaults */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEntryDefaults"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listWallets: {
        parameters: {
            query?: {
                /** @description End-of-day balance date, YYYY-MM-DD */
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The owner's wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletCollection"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header: {
                /** @description A client-generated key naming this one creation */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description The created wallet, or the original on a replay */
            201: {
                headers: {
                    /** @description Where the created wallet can be retrieved */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different payload */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The wallet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The wallet was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Wallet still has transactions or history */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HistoryRemainsProblem"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    changeWalletArchiveState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletArchiveStateRequest"];
            };
        };
        responses: {
            /** @description The wallet with its changed archived state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replaceWalletOpening: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletOpeningRequest"];
            };
        };
        responses: {
            /** @description The wallet with its replaced opening balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Command is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
