import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { OPENAPI_DOCUMENT_PATH } from "@bookkeeping/server/src/core/http/openapi.js";
import { createUnitTestApp } from "@bookkeeping/server/src/testing/create-unit-test-app.js";
import openapiTS, { astToString } from "openapi-typescript";

// The client is generated from the server's own OpenAPI document, served by
// the same app factory the server's contract tests use, so no server needs to
// run and no database is reached. Both outputs are committed; `--check` writes
// nothing and fails the build when they no longer match what the server
// publishes.
const DOCUMENT_FILE = new URL("../src/core/api/openapi.json", import.meta.url);
const TYPES_FILE = new URL("../src/core/api/openapi.gen.ts", import.meta.url);
const GENERATED_HEADER =
  "// Generated by `pnpm --filter @bookkeeping/web generate:api` from the\n" +
  "// server's OpenAPI document. Do not edit; regenerate.\n\n";

async function fetchServerDocument(): Promise<string> {
  const response = await createUnitTestApp().request(OPENAPI_DOCUMENT_PATH);
  if (!response.ok) {
    throw new Error(
      `The server answered ${response.status} for ${OPENAPI_DOCUMENT_PATH}`,
    );
  }
  return `${JSON.stringify(await response.json(), null, 2)}\n`;
}

async function generateTypes(document: string): Promise<string> {
  // Sorted members keep the committed file's diffs down to real changes.
  const ast = await openapiTS(JSON.parse(document), { alphabetize: true });
  return `${GENERATED_HEADER}${astToString(ast)}`;
}

async function readIfPresent(file: URL): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

interface GeneratedFile {
  file: URL;
  content: string;
}

/** Returns the generated files whose content differs from the files on disk. */
async function findChangedFiles(): Promise<GeneratedFile[]> {
  const document = await fetchServerDocument();
  const types = await generateTypes(document);
  const generated: GeneratedFile[] = [
    { file: DOCUMENT_FILE, content: document },
    { file: TYPES_FILE, content: types },
  ];
  const changed: GeneratedFile[] = [];
  for (const entry of generated) {
    if ((await readIfPresent(entry.file)) !== entry.content) {
      changed.push(entry);
    }
  }
  return changed;
}

const checkOnly = process.argv.includes("--check");
const changed = await findChangedFiles();
const changedPaths = changed.map(({ file }) => `  ${fileURLToPath(file)}`);

if (checkOnly) {
  if (changed.length > 0) {
    console.error(
      [
        "The generated API client no longer matches the server:",
        ...changedPaths,
        "Run `pnpm --filter @bookkeeping/web generate:api` and commit the result.",
      ].join("\n"),
    );
    process.exit(1);
  }
  console.log(
    "The committed API client matches the server's OpenAPI document.",
  );
} else if (changed.length > 0) {
  for (const { file, content } of changed) {
    await writeFile(file, content);
  }
  console.log(`Regenerated:\n${changedPaths.join("\n")}`);
} else {
  console.log("The API client is already up to date.");
}
