import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { OPENAPI_DOCUMENT_PATH } from "@bookkeeping/server/src/core/http/openapi.js";
import { createUnitTestApp } from "@bookkeeping/server/src/testing/create-unit-test-app.js";
import openapiTS, { astToString } from "openapi-typescript";

// The client is generated from the server's own OpenAPI document, served by
// the same app factory the server's contract tests use, so no server needs to
// run and no database is reached. Both outputs are committed; `--check` fails
// the build when they no longer match what the server publishes.
const DOCUMENT_FILE = new URL("../src/core/api/openapi.json", import.meta.url);
const TYPES_FILE = new URL("../src/core/api/openapi.gen.ts", import.meta.url);
const GENERATED_FILES = [DOCUMENT_FILE, TYPES_FILE].map((file) =>
  fileURLToPath(file),
);
const GENERATED_HEADER =
  "// Generated by `pnpm --filter @bookkeeping/web generate:api` from the\n" +
  "// server's OpenAPI document. Do not edit; regenerate.\n\n";

async function fetchServerDocument(): Promise<string> {
  const response = await createUnitTestApp().request(OPENAPI_DOCUMENT_PATH);
  if (!response.ok) {
    throw new Error(
      `The server answered ${response.status} for ${OPENAPI_DOCUMENT_PATH}`,
    );
  }
  return `${JSON.stringify(await response.json(), null, 2)}\n`;
}

async function generateTypes(document: string): Promise<string> {
  // Sorted members keep the committed file's diffs down to real changes.
  const ast = await openapiTS(JSON.parse(document), { alphabetize: true });
  return `${GENERATED_HEADER}${astToString(ast)}`;
}

async function readIfPresent(file: URL): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

/** Writes the outputs and reports which committed files changed, if any. */
async function generate(): Promise<string[]> {
  const document = await fetchServerDocument();
  const types = await generateTypes(document);
  const changed: string[] = [];

  for (const [file, content] of [
    [DOCUMENT_FILE, document],
    [TYPES_FILE, types],
  ] as const) {
    if ((await readIfPresent(file)) !== content) {
      changed.push(fileURLToPath(file));
    }
    await writeFile(file, content);
  }

  return changed;
}

/** True when the file is committed as generated: tracked, unmodified, unstaged. */
function isCommittedAsGenerated(file: string): boolean {
  const status = execFileSync(
    "git",
    ["status", "--porcelain", "--untracked-files=all", "--", file],
    { encoding: "utf8" },
  );
  return status.trim() === "";
}

const checkOnly = process.argv.includes("--check");
const changed = await generate();

if (checkOnly) {
  const drifted = GENERATED_FILES.filter(
    (file) => !isCommittedAsGenerated(file),
  );
  if (drifted.length > 0) {
    console.error(
      [
        "The generated API client differs from what is committed:",
        ...drifted.map((file) => `  ${file}`),
        "Run `pnpm --filter @bookkeeping/web generate:api` and commit the result.",
      ].join("\n"),
    );
    process.exit(1);
  }
  console.log(
    "The committed API client matches the server's OpenAPI document.",
  );
} else if (changed.length > 0) {
  console.log(`Regenerated:\n${changed.map((file) => `  ${file}`).join("\n")}`);
} else {
  console.log("The API client is already up to date.");
}
