/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppWalletsIndexRouteImport } from './routes/_app/wallets/index'
import { Route as AppWalletsWalletIdRouteImport } from './routes/_app/wallets/$walletId'
import { Route as AppWalletsNewRouteImport } from './routes/_app/wallets/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsWalletIdRoute = AppWalletsWalletIdRouteImport.update({
  id: '/wallets/$walletId',
  path: '/wallets/$walletId',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsNewRoute = AppWalletsNewRouteImport.update({
  id: '/wallets/new',
  path: '/wallets/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/wallets/new': typeof AppWalletsNewRoute
  '/wallets/': typeof AppWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/wallets/new': typeof AppWalletsNewRoute
  '/wallets': typeof AppWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/_app/wallets/new': typeof AppWalletsNewRoute
  '/_app/wallets/': typeof AppWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/wallets/$walletId'
    | '/wallets/new'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/wallets/$walletId'
    | '/wallets/new'
    | '/wallets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/wallets/$walletId'
    | '/_app/wallets/new'
    | '/_app/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/wallets/': {
      id: '/_app/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallets/$walletId': {
      id: '/_app/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof AppWalletsWalletIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallets/new': {
      id: '/_app/wallets/new'
      path: '/wallets/new'
      fullPath: '/wallets/new'
      preLoaderRoute: typeof AppWalletsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppWalletsWalletIdRoute: typeof AppWalletsWalletIdRoute
  AppWalletsNewRoute: typeof AppWalletsNewRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWalletsWalletIdRoute: AppWalletsWalletIdRoute,
  AppWalletsNewRoute: AppWalletsNewRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
